locations:
    rename: [591, 1090]
    next: [1020, 600]
    keyboard_ok: [933, 1365]
    rename_ok: [540, 1250]
    close_calcy_dialog: [966, 1092]
    edit_box: [90, 1090] # only used with --touch-paste
    paste: [483, 1092] # only used with --touch-paste
    favorite_button: [980, 156]
    favorite_button_box: [960, 142, 1001, 180]
    pokemon_menu_button: [933, 1777]
    appraise_button: [934, 1377]
    continue_appraisal: [590, 1770]
    calcy_appraisal_save_button: [855, 1000]
    dismiss_calcy: [555, 1296]
    appraisal_box: [45, 1664, 1032, 1872]

waits:
    next: 0.5
    rename: 0.5
    rename_ok: 1
    pokemon_menu_button: 1
    appraise_button: 1

blacklist:
    - MewThree

actions:
    - conditions:
        success: false
      actions:
        rename: ".FAILED"
    - conditions:
        iv__in: [0, 100]
      actions:
        favorite:
        rename-calcy:
    - actions:
        rename-calcy: # Rename normally


iv_regexes:
    - ^(?P<iv_min>\d+)\-(?P<iv_max>\d+).*$
    - ^(?P<iv>\d+).*$
